name: UHPSampleEngine C++ CI Build

env:
  Product: UHPSampleEngineCpp

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/engines_cpp_ci.yml'
      - 'engines/cpp/**'
      - '!engines/cpp/*.md'

defaults:
  run:
    shell: pwsh

jobs:
  ci_build_windows:
    name: CI Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} ..
        cmake --build . --config ${{ matrix.configuration }}
      working-directory: ./engines/cpp/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Product }}.Windows.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: ./engines/cpp/build/${{ matrix.configuration }}/*

  ci_build_linux:
    name: CI Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ matrix.configuration }}/
        cmake --build . --config ${{ matrix.configuration }}
      working-directory: ./engines/cpp/
    
    - name: Tar Files
      run: tar -C build/${{ matrix.configuration }} . -cvzf ${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz
      working-directory: ./engines/cpp/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: ./engines/cpp/${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz